inventory:
  #Inventory size (must be a multiple of 9)
  size: 18
  #Inventory title
  title: "Bookshelf"

# Worlds to disable bookshelves in
disabledWorlds: []

# Whether to allow only books in shelves
onlyBooks: true

# Hopper support
hoppers: false

# Material-restrictions
# IMPORTANT: Restrictions only work when onlyBooks is set to false
restrictions:

  # When true restrictions will be enabled
  enabled: false

  # When true the material-list will be used as whitelist
  whitelist: true

  # Define the restricted/whitelisted materials below
  materials:
    - BOOK
    - WRITABLE_BOOK
    - WRITTEN_BOOK
    - ENCHANTED_BOOK